clone_depth: 1
version: '{branch}-{build}'
image: Visual Studio 2017
configuration: Debug
cache:
  - C:\ProgramData\chocolatey\bin -> appveyor.yml
  - C:\ProgramData\chocolatey\lib -> appveyor.yml
  - inspectcode -> appveyor.yml
  - packages -> **\packages.config
install:
  - cmd: git submodule update --init --recursive --depth=5
  - cmd: choco install resharper-clt -y
  - cmd: choco install nvika -y
before_build:
  - cmd: nuget restore -verbosity quiet
environment:
  TargetFramework: net471
build:
  project: osu.sln
  parallel: true
  verbosity: minimal
after_build:
  - cmd: inspectcode --o="inspectcodereport.xml" --projects:touhou.sharp.Game* --caches-home="inspectcode" "Touhou Sharp.sln" > NUL
  - cmd: NVika parsereport "inspectcodereport.xml" --treatwarningsaserrors